### ISSUE TITLE
LỖI: hiển thị bảng chi tiết thực phẩm 2 lần

### ISSUE THREAD

**Issue by FuongKuynh** [Huy-nguyen-here/CalCal#4]
Lỗi hiển thị bảng chi tiết thực phẩm: Khi thêm số lượng thực phẩm và đã tính toán lượng Calo. Bấm vào Chi tiết để xem bảng thực phẩm các hàng giá trị bị lặp lại 2 lần.
Chi tiết:
File food_calo_in.cpp
hàm void food_calo_in (29 ->52)

**Comment by huynq2004** [comment]
Huy đã sửa lỗi này trong phiên bản mới của phần mềm ở nhánh Tính năng 3 nhé.
